# Site settings
title: MacBen's Blog
email: pocketkids@gmail.com
description: "Just for fun."
baseurl: "pocketkids.github.io"
url: "http://pocketkids.github.io"

# Build settings
markdown: kramdown
permalink: pretty
