# Site settings
title: MacBen
username: pocketkids
email: pocketkids@gmail.com
description: "Just for fun."
baseurl: ""
url: "http://pocketkids.github.io"

# Build settings
markdown: kramdown
permalink: pretty
