# Site settings
title: MacBen
email: pocketkids@gmail.com
username: "pocketkids"
description: "Just for fun."
baseurl: ""
url: "http://pocketkids.github.io"

# Build settings
markdown: kramdown
permalink: pretty
